// Skills dictionary (700+ skills, grouped) and a matcher used by the ATS checker and the job description analyzer.
// Entry syntax: Name|alias1,alias2   Trailing ! on the name = case-sensitive (ambiguous words), @ = only inside a list (C, R, Go).

const RAW = {
  'Programming languages': `JavaScript|js,ecmascript,es6;TypeScript|ts;Python|python3;Java;C#|csharp,c sharp;C++|cpp;C@;Go@|golang;Rust!;Ruby!;PHP;Swift!;Kotlin;Scala;R@;MATLAB;Perl;Dart!;Lua;Haskell;Elixir;Erlang;Clojure;Objective-C|objc;Groovy;Bash|shell scripting,shell script;PowerShell;SQL;PL/SQL|plsql;T-SQL|tsql;VBA|visual basic for applications;COBOL;Fortran;Assembly|assembly language;Solidity;F#|fsharp;Visual Basic|vb.net;SAS!;Apex!;ABAP;Scheme;OCaml;Prolog;Verilog;VHDL`,
  'Frontend': `React|react.js,reactjs;Next.js|nextjs;Vue.js|vue,vuejs;Nuxt|nuxt.js;Angular|angularjs;Svelte;SvelteKit;Redux;Redux Toolkit;Zustand;MobX;jQuery;HTML|html5;CSS|css3;Sass|scss;Less!;Tailwind CSS|tailwind;Bootstrap;Material UI|mui,material-ui;Chakra UI;Ant Design;Webpack;Vite;Babel;Rollup;Gatsby;Remix!;Astro!;Storybook;Web Components;WebSockets|websocket;Progressive Web Apps|pwa;Responsive design|responsive web design;Accessibility|wcag,a11y;Three.js|threejs;D3.js|d3;Ember.js|ember;Backbone.js|backbone;Electron;Webflow;Micro frontends|micro-frontends;Single page applications|spa;Cross-browser compatibility;Web performance;Core Web Vitals;SSR|server-side rendering;Browser extensions`,
  'Backend and APIs': `Node.js|nodejs;Express!|express.js~,expressjs~;NestJS|nest.js;Django;Flask;FastAPI;Spring Boot|springboot;Spring Framework|spring mvc,spring cloud,spring data,spring framework;Hibernate;.NET|dotnet,.net core;ASP.NET;Laravel;Symfony;Ruby on Rails|rails;Sinatra;Micronaut;Quarkus;gRPC;Microservices|microservice;REST APIs|rest api,restful,restful apis,rest;GraphQL;SOAP;OAuth|oauth2;JWT|json web tokens;OpenAPI|swagger;API design;API development;API integration;Event-driven architecture;Domain-driven design|ddd;Clean architecture;System design;Distributed systems;Multithreading|multi-threading;Concurrency;Message queues;Webhooks;Serverless;Backend development;Object-oriented programming|oop,object oriented programming;Functional programming;Design patterns;Data structures;Algorithms;Scalability`,
  'Databases': `PostgreSQL|postgres;MySQL;MariaDB;SQL Server|mssql,microsoft sql server;Oracle Database|oracle db;SQLite;MongoDB|mongo;Cassandra;DynamoDB;Redis;Memcached;Neo4j;CouchDB;Couchbase;Firebase|firestore;Supabase;Snowflake;BigQuery;Redshift;Databricks;ClickHouse;Presto|trino;Apache Hive|hive;HBase;Teradata;InfluxDB;TimescaleDB;Elasticsearch|elastic search;OpenSearch;Solr;Data modeling|data modelling;Data warehousing|data warehouse;ETL;ELT;Database design;Query optimization;Stored procedures;NoSQL;Database administration|dba;Replication;Sharding;Indexing;ORM|prisma,sequelize,sqlalchemy`,
  'Cloud and DevOps': `AWS|amazon web services;Azure|microsoft azure;GCP|google cloud,google cloud platform;EC2;S3;Lambda|aws lambda;ECS;EKS;RDS;CloudFormation;Terraform;Ansible;Puppet;Chef!;Docker;Kubernetes|k8s;Helm;OpenShift;Jenkins;GitHub Actions;GitLab CI|gitlab;CircleCI;Travis CI;ArgoCD|argo cd;CI/CD|cicd,continuous integration,continuous delivery,continuous deployment;Git;GitHub;Bitbucket;Linux;Unix;Windows Server;Prometheus;Grafana;Datadog;New Relic;Splunk;ELK Stack|elk;Nagios;PagerDuty;Observability;Monitoring;SRE|site reliability engineering;DevOps;DevSecOps;Infrastructure as code|iac;Vagrant;VMware;Virtualization;Load balancing;CDN;Cloudflare;Vercel;Netlify;Heroku;DigitalOcean;Istio;Service mesh;Networking;TCP/IP;DNS;VPN;Firewalls|firewall;IAM;HashiCorp Vault|vault!;Nginx;Apache HTTP Server;Tomcat;Kafka|apache kafka;RabbitMQ;Capacity planning;Disaster recovery;High availability;Cost optimization|finops;Cloud migration;Cloud architecture`,
  'Data, ML and AI': `Machine learning|ml;Deep learning;NLP|natural language processing;Computer vision;Reinforcement learning;LLMs|llm,large language models;Generative AI|genai,gen ai;Prompt engineering;RAG|retrieval augmented generation,retrieval-augmented generation;TensorFlow;PyTorch;Keras;scikit-learn|sklearn;XGBoost;LightGBM;Hugging Face|huggingface;LangChain;OpenAI;Pandas;NumPy;SciPy;Matplotlib;Seaborn;Plotly;Jupyter;Apache Spark|spark!,pyspark;Hadoop;Airflow|apache airflow;dbt;Dagster;Flink;MLflow;Kubeflow;SageMaker;Tableau;Power BI|powerbi;Looker;Qlik|qlikview,qlik sense;Metabase;Superset;Excel!|microsoft excel~,ms excel~;Google Sheets;Data analysis;Data analytics;Data visualization|data visualisation;Statistics|statistical analysis;Statistical modeling;A/B testing|ab testing,a/b tests;Hypothesis testing;Regression;Classification;Clustering;Time series;Forecasting;Feature engineering;Data mining;Data cleaning|data wrangling,data cleansing;Data pipelines|data pipeline;Data engineering;Data governance;Data science;Business intelligence|bi reporting;OCR;Recommender systems|recommendation systems;MLOps;Big data;Predictive modeling|predictive modelling;Bayesian;Mathematical optimization|linear programming;Anomaly detection;Neural networks;Transformers!;Data quality;Dashboards|dashboard;Reporting;Pivot tables|pivot table;VLOOKUP|xlookup;Power Query;DAX;Alteryx;Stata;SPSS;Predictive analytics;Web scraping|scraping`,
  'Mobile': `Android;iOS;React Native;Flutter;SwiftUI;Jetpack Compose;Xamarin;Ionic;Cordova;Kotlin Multiplatform;App Store|app store optimization;Mobile development|mobile app development;Android Studio;Xcode;Core Data;Push notifications`,
  'Testing and QA': `Selenium;Cypress;Playwright;Jest;Mocha;JUnit;TestNG;PyTest;Postman;JMeter;Appium;Cucumber;Test automation|automation testing;Unit testing|unit tests;Integration testing;Regression testing;Performance testing;Load testing;Manual testing;Quality assurance|qa;TDD|test-driven development,test driven development;BDD|behavior-driven development;SonarQube;UAT|user acceptance testing;Test planning|test plans;Bug tracking;End-to-end testing|e2e testing;Test cases;API testing;Code review|code reviews;Debugging;Root cause analysis|rca;Smoke testing;Exploratory testing;Accessibility testing`,
  'Security and compliance': `Cybersecurity|cyber security;Information security|infosec;Penetration testing|pentesting,pen testing;Vulnerability assessment|vulnerability management;SIEM;SOC;Threat modeling|threat modelling;OWASP;Encryption|cryptography;Zero trust;ISO 27001;SOC 2;GDPR;HIPAA;PCI DSS|pci-dss;Incident response;Network security;Application security|appsec;Cloud security;Nessus;Burp Suite;Metasploit;Wireshark;Risk assessment;Compliance;Endpoint security;Identity management;SSO|single sign-on;Security awareness;Forensics|digital forensics;Malware analysis;Business continuity;Governance risk and compliance|grc`,
  'Design and creative': `UX design|user experience,ux;UI design|user interface,ui;Figma;Sketch!;Adobe XD;Photoshop|adobe photoshop;Illustrator|adobe illustrator;InDesign|adobe indesign;After Effects|adobe after effects;Premiere Pro|adobe premiere;Canva;Wireframing|wireframes;Prototyping|prototypes;User research;Usability testing;Design systems|design system;Interaction design;Visual design;Information architecture;Typography;Branding|brand identity;Motion graphics;Video editing;3D modeling|3d modelling;Blender;AutoCAD;SolidWorks;Graphic design;Illustration;User personas|personas;Journey mapping|user journey;Lightroom|adobe lightroom;Final Cut Pro;DaVinci Resolve;Maya;Cinema 4D;Art direction;Creative direction;Layout design;Packaging design;Photography;Storyboarding;Sound design;Audio editing`,
  'Product and project management': `Product management;Product strategy;Roadmapping|product roadmap,roadmaps;Product discovery;User stories;Backlog grooming|backlog refinement,backlog management;Agile|agile methodology;Scrum;Kanban;SAFe|scaled agile;Waterfall;Lean!;Six Sigma;PMP|project management professional;PRINCE2;Jira;Confluence;Asana;Trello;Monday.com;Notion!;Linear!;OKRs|okr;KPIs|kpi,key performance indicators;Stakeholder management|stakeholder engagement;Go-to-market|gtm strategy,go to market;Product launch;Competitive analysis|competitor analysis;Market research;Customer discovery;MVP|minimum viable product;Prioritization|prioritisation;Product analytics;Amplitude;Mixpanel;Google Analytics|ga4;Hotjar;Project management;Program management|programme management;Risk management;Change management;Resource planning|resource allocation;Sprint planning;Retrospectives|retrospective;Release management;Project planning;Gantt charts|gantt;Budget management|budget ownership;Cross-functional teams|cross functional;Product requirements|prd;Product-market fit;Feature prioritization;Customer feedback`,
  'Marketing and content': `Digital marketing;SEO|search engine optimization;SEM|search engine marketing;PPC|pay per click,pay-per-click;Google Ads|adwords;Facebook Ads|meta ads;LinkedIn Ads;Social media marketing|smm;Content marketing;Content strategy;Copywriting;Email marketing;Marketing automation;HubSpot;Marketo;Mailchimp;Klaviyo;Salesforce Marketing Cloud;Pardot;Brand management|brand strategy;Influencer marketing;Affiliate marketing;Growth marketing|growth hacking;Conversion rate optimization|cro;Marketing analytics;Google Tag Manager;SEMrush;Ahrefs;Moz;WordPress;Shopify;WooCommerce;Magento;Wix;Public relations|pr!;Event marketing;Demand generation|demand gen;Lead generation|lead gen;Account-based marketing|abm;Video marketing;Podcasting;Storytelling;Editing;Proofreading;Technical writing;Blogging;Social media management;Community management;Hootsuite;Buffer;Sprout Social;Campaign management;Performance marketing;Customer acquisition;Market segmentation;Newsletter;Content creation;Ecommerce|e-commerce;Product marketing;Marketing strategy;Press releases;Media relations;Audience growth;Copy editing;UX writing;Search ads;Display advertising|programmatic advertising`,
  'Sales and customer success': `Sales;B2B sales|b2b;B2C;SaaS sales|saas;Lead qualification;Prospecting;Cold calling;Negotiation;Account management;Key account management;Business development;CRM|customer relationship management;Salesforce;Zoho CRM|zoho;Pipedrive;Sales forecasting;Pipeline management|sales pipeline;Closing deals|closing;Upselling;Cross-selling;Customer success;Customer retention;Churn reduction|churn;Territory management;Solution selling;Consultative selling;Inside sales;Outbound sales;Channel sales;Partner management|partnerships;RFP|request for proposal;Proposal writing;Contract negotiation;Quota attainment|quota;Revenue growth;Lead nurturing;Sales enablement;Sales operations|sales ops;Customer onboarding;Renewals;Enterprise sales;Account executive;Sales strategy;Customer engagement;Retail sales;Cold outreach;Sales presentations;Gong;Outreach.io|outreach!;ZoomInfo;Apollo.io`,
  'Customer support': `Customer support;Customer service;Technical support;Help desk|helpdesk;Ticketing systems|ticketing;Call center|call centre;Live chat;Escalation management;SLA management|sla;Zendesk;Freshdesk;Intercom;ServiceNow;Troubleshooting;Customer experience|cx;NPS|net promoter score;CSAT|customer satisfaction;First call resolution;Knowledge base;Complaint handling;Phone support;Email support;Technical troubleshooting`,
  'Finance and accounting': `Financial analysis;Financial modeling|financial modelling;Budgeting;Variance analysis;Accounts payable|ap process;Accounts receivable|ar process;General ledger;Bookkeeping;Reconciliation|bank reconciliation;Month-end close|month end close;Financial reporting;GAAP;IFRS;Ind AS;Taxation|tax compliance;GST;TDS;Income tax;Internal controls;SOX|sarbanes-oxley;Payroll;QuickBooks;Tally|tally erp,tally prime;SAP|sap erp,sap fico;Oracle Financials;NetSuite;Xero;Zoho Books;Treasury;Cash flow|cash flow management;Valuation;DCF|discounted cash flow;M&A|mergers and acquisitions;Investment banking;Equity research;Portfolio management;Risk analysis;Credit analysis;Underwriting;Derivatives;Bloomberg|bloomberg terminal;FP&A|financial planning and analysis;Cost accounting;Management accounting;Consolidation|financial consolidation;CPA;CFA;ACCA;Auditing|statutory audit,internal audit;Accruals;Invoicing;Expense management;Procurement to pay|p2p;Order to cash|o2c;Fixed assets;Working capital;Financial planning;Fund accounting;Transfer pricing;Anti-money laundering|aml;KYC|know your customer;Banking;Wealth management;Mutual funds;Capital markets;Fintech|financial technology;Pricing strategy;Unit economics;Revenue recognition`,
  'HR and recruiting': `Talent acquisition;Recruiting|recruitment;Sourcing|candidate sourcing;Applicant tracking|ats;Onboarding;Employee engagement;Performance management;Compensation and benefits|compensation & benefits,c&b;HRIS;Workday;BambooHR;SuccessFactors;Employee relations;Learning and development|l&d;Training|training programs;HR analytics|people analytics;Labor law|labour law;Diversity and inclusion|dei;Succession planning;Workforce planning;Interviewing|interview process;Employer branding;Offboarding;Coaching;Mentoring;Talent management;Organizational development;HR business partner|hrbp;Policy development;Grievance handling;Campus hiring|campus recruitment;Headhunting;Executive search;Culture building;Employee retention;Statutory compliance`,
  'Operations and supply chain': `Supply chain management|scm,supply chain;Logistics;Procurement;Vendor management|supplier management;Inventory management|inventory control;Demand planning;Warehouse management|wms,warehousing;Lean manufacturing;Kaizen;5S;Quality control|qc;ISO 9001;Process improvement|continuous improvement;Process optimization|process optimisation;Operations management;Production planning;Manufacturing;Import export|exim;Freight|freight forwarding;Last mile delivery|last-mile;ERP|enterprise resource planning;MRP;FMEA;SPC|statistical process control;Value stream mapping;Total quality management|tqm;Fleet management;Cold chain;Order management;Facilities management;Standard operating procedures|sop,sops;Cost reduction;Capacity management;Production management;Quality management systems|qms;Customs clearance;Dispatch;Shipping;Merchandising;Category management;Retail operations;Store operations;Event management;Hospitality management;Travel planning`,
  'Business and consulting': `Business analysis;Requirements gathering|requirement gathering;Process mapping;BPMN;UML;Gap analysis;SWOT analysis|swot;Business case;Cost-benefit analysis;Market analysis;Competitive intelligence;Strategic planning;Business strategy;Consulting|management consulting;Due diligence;Stakeholder analysis;Business modeling|business model;Business transformation;Operating model;Benchmarking;Executive reporting;Data-driven decision making|data-driven;Feasibility study;Strategic partnerships;Entrepreneurship;Startup experience|startups;P&L management|p&l;Revenue operations|revops;Business operations;Process automation|rpa;UiPath;Automation Anywhere`,
  'Legal and policy': `Contract drafting;Legal research;Corporate law;Intellectual property|ip law,patents;Litigation;Regulatory compliance;Privacy|data privacy;Contract management;Policy analysis;Legal writing;Corporate governance;Company secretary|cs;Trademark;Negotiating contracts;Employment law;Real estate law;Arbitration;Legal drafting;Paralegal;E-discovery;Regulatory affairs`,
  'Healthcare and science': `Patient care;Clinical research;EMR|electronic medical records;EHR|electronic health records;Medical coding;ICD-10;Pharmacology;Nursing;Telehealth|telemedicine;Epic Systems;Clinical trials;Basic life support|bls;CPR;Public health;Biostatistics;Pharmacovigilance;Medical writing;Laboratory skills|lab skills;PCR;Cell culture;Bioinformatics;Genomics;Chromatography|hplc;Quality assurance in pharma|gmp;Physiotherapy;Radiology;Diagnostics;Patient education;Medical devices`,
  'Engineering and manufacturing': `AutoCAD;SolidWorks;CATIA;ANSYS;Simulink;PLC|plc programming;SCADA;CAD;CAM;CNC|cnc machining;GD&T;FEA|finite element analysis;CFD|computational fluid dynamics;PCB design;Embedded systems|embedded c;Arduino;Raspberry Pi;FPGA;RTOS;Robotics;ROS|robot operating system;Circuit design;Power systems;HVAC;Civil engineering;Structural analysis;STAAD|staad.pro;Revit;BIM|building information modeling;Primavera;Surveying;Thermodynamics;Mechanical design;Electrical design;Welding;Mechatronics;Control systems;Signal processing;IoT|internet of things;3D printing;Prototype development;Technical drawings;Project estimation;Site supervision;Fabrication;Industrial automation;Reliability engineering;Failure analysis;Instrumentation;Manufacturing engineering;Process engineering;Chemical engineering;Materials science`,
  'Education and training': `Curriculum development;Lesson planning;Classroom management;Instructional design;E-learning|elearning;LMS|learning management system;Tutoring;Training delivery;Assessment design;Teaching;Public speaking;Workshop facilitation;Student engagement;Moodle;Articulate Storyline|storyline;Academic writing;Research methodology;Grant writing;Literature review;Peer review;Course design;Curriculum design;Mentorship programs`,
  'Tools and office': `Microsoft Office|ms office,office 365,microsoft 365;Word!|microsoft word~;PowerPoint|ms powerpoint;Outlook;Google Workspace|g suite;Slack;Microsoft Teams|ms teams;Zoom;SharePoint;Visio;Access!;Power Automate;Power Apps;Zapier;Airtable;Smartsheet;Lucidchart;Miro;Dynamics 365;Google Docs;Google Drive;Dropbox;DocuSign;Calendly;Typing speed;Data entry;MS Project|microsoft project;Notion AI;ChatGPT;Claude;Copilot|github copilot,microsoft copilot;Make.com;n8n`,
  'Soft skills': `Communication|communication skills;Leadership;Teamwork|collaboration;Problem solving|problem-solving;Critical thinking;Time management;Adaptability|flexibility;Creativity;Emotional intelligence;Conflict resolution;Decision making|decision-making;Attention to detail|detail-oriented;Multitasking;Presentation skills;Analytical skills|analytical thinking;Strategic thinking;Interpersonal skills;Work ethic;Self-motivated|self-starter,self motivated;Ownership|accountability;Cross-functional collaboration;Active listening;Empathy;Organizational skills|organisational skills;Initiative;Resilience;Written communication|writing skills;Verbal communication;Remote work|remote collaboration;People management|team management;Team building;Influencing;Facilitation;Mentoring skills;Customer focus;Results-oriented|results driven;Curiosity;Continuous learning|fast learner,quick learner;Positive attitude;Reliability;Professionalism;Negotiation skills;Stress management;Cultural awareness;English|english proficiency;Hindi;Bilingual|multilingual`,
}

export const CATEGORY_ORDER = Object.keys(RAW)

function build() {
  const out = []
  for (const [cat, line] of Object.entries(RAW)) {
    for (const part of line.split(';')) {
      const [namePart, aliasPart = ''] = part.trim().split('|')
      if (!namePart) continue
      const flag = /[!@]$/.test(namePart) ? namePart.slice(-1) : ''
      const name = flag ? namePart.slice(0, -1) : namePart
      const aliases = aliasPart.split(',').map((a) => a.trim()).filter(Boolean)
      // aliases may carry their own case flag
      const forms = [{ t: name, flag }, ...aliases.map((a) => (/[!@~]$/.test(a) ? { t: a.slice(0, -1), flag: a.slice(-1) === '~' ? '' : a.slice(-1) } : { t: a, flag }))]
      out.push({ name, cat, forms })
    }
  }
  return out
}

export const SKILLS = build()
export const SKILL_COUNT = SKILLS.length

const escRe = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
let compiled = null
const SEP = '[,;|/\u2022\u00b7(\\n]'
function compile() {
  if (compiled) return compiled
  compiled = SKILLS.map((sk) => {
    const groups = { ci: new Set(), cs: new Set(), bare: new Set() }
    for (const { t, flag } of sk.forms) groups[flag === '@' ? 'bare' : flag === '!' ? 'cs' : 'ci'].add(escRe(t).replace(/[\s-]+/g, '[\\s\\-]+'))
    const alt = (set) => [...set].sort((x, y) => y.length - x.length).join('|')
    const parts = []
    if (groups.ci.size) parts.push(new RegExp(`(?<![\\p{L}\\p{N}_+#.])(?:${alt(groups.ci)})(?![\\p{L}\\p{N}+#])`, 'gimu'))
    if (groups.cs.size) parts.push(new RegExp(`(?<![\\p{L}\\p{N}_+#.])(?:${alt(groups.cs)})(?![\\p{L}\\p{N}+#])`, 'gmu'))
    if (groups.bare.size) parts.push(new RegExp(`(?:^|${SEP}\\s*|\\b(?:and|or)\\s+)(?:${alt(groups.bare)})(?=\\s*(?:[,;|/)\u2022\u00b7\\n]|$))`, 'gmu'))
    return { name: sk.name, cat: sk.cat, parts }
  })
  return compiled
}

/** Find dictionary skills in text. Returns [{name, cat, count, index}] sorted by first appearance. */
export function findSkills(text) {
  const out = []
  const src = ` ${text || ''} `
  for (const sk of compile()) {
    let count = 0, index = Infinity
    for (const re of sk.parts) {
      re.lastIndex = 0
      let m
      while ((m = re.exec(src))) {
        count++
        index = Math.min(index, m.index)
        if (m[0].length === 0) re.lastIndex++
      }
    }
    if (count) out.push({ name: sk.name, cat: sk.cat, count, index })
  }
  return out.sort((a, b) => a.index - b.index)
}

export const STOPWORDS = new Set(`a about above after again against all also am an and any are as at be because been before being below between both but by can cannot could did do does doing down during each few for from further had has have having he her here hers him his how i if in into is it its just me more most my no nor not now of off on once only or other our out over own same she should so some such than that the their them then there these they this those through to too under until up very was we were what when where which while who whom why will with would you your yours able across within including etc us per via ability join work working team teams role roles position candidate candidates company job opportunity looking seeking responsible will plus new well like make get must should may might need needs needed strong good great excellent years year experience experienced preferred required requirements responsibilities qualifications skills knowledge understanding using use used based help helping ensure provide support develop developing build building create creating`.split(/\s+/))
