// Pack career: resumes, letters, emails, meetings and presentations. Default category: career.
export const cat = 'career'
export default [
  { id: 'resume-builder', name: 'Resume / CV builder', desc: 'Build an ATS-friendly resume with a live PDF preview, drag-to-reorder sections and Word export.', icon: 'file-user', tags: 'cv resume builder template ats pdf docx', ready: true },
  { id: 'resume-to-pdf', name: 'Resume to PDF', module: 'resume-builder', params: { export: 'pdf' }, desc: 'Turn your resume content into a polished PDF with real, selectable text that ATS software can read.', icon: 'file-down', tags: 'cv pdf export download', ready: true },
  { id: 'resume-to-word', name: 'Resume to Word', module: 'resume-builder', params: { export: 'docx' }, desc: 'Export your resume as a clean, editable .docx file with real bullet lists.', icon: 'file-type', tags: 'cv docx word export download', ready: true },
  { id: 'resume-formatter', name: 'Resume formatter', module: 'resume-builder', params: { import: true }, also: ['text'], desc: 'Paste or upload an old resume (PDF, DOCX, TXT) and reformat it into a clean template.', icon: 'wand-sparkles', tags: 'reformat cv clean template import parse', ready: true },
  { id: 'ats-checker', name: 'Resume ATS checker', desc: 'Score your resume against a job description, find missing keywords and fix ATS red flags.', icon: 'scan-search', tags: 'ats keywords score job match resume check', ready: true },
  { id: 'cover-letter', name: 'Cover letter generator', desc: 'Draft a cover letter from a few fields in four tones, edit it, and download as Word or PDF. AI tailoring optional.', icon: 'mail-open', tags: 'cover letter application job', ready: true },
  { id: 'jd-analyzer', name: 'Job description analyzer', desc: 'Pull out skills, years, pay, requirements, red flags and keywords from a job post as you paste it.', icon: 'file-search', tags: 'job description skills keywords salary red flags', ready: true },
  { id: 'linkedin-bio', name: 'LinkedIn bio generator', desc: 'Write headline options (220 characters) and About drafts (2,600) with live counters. AI polish optional.', icon: 'user-round-pen', tags: 'linkedin headline about summary bio', ready: true },
  { id: 'email-generator', name: 'Email generator', desc: '39 professional email templates: leave, resignation, follow-up, salary, complaints and more, in three tones.', icon: 'mail-plus', tags: 'email template professional leave resignation follow up mailto', ready: true },
  { id: 'email-rewriter', name: 'Email rewriter', desc: 'Rewrite an email in the tone and length you want and compare it word by word with the original.', icon: 'pen-line', mode: 'ai', tags: 'rewrite tone polite formal shorter grammar', ready: true },
  { id: 'meeting-notes', name: 'Meeting notes generator', desc: 'Structured minutes with attendees, decisions and action items. Export Markdown, Word or PDF.', icon: 'notebook-pen', tags: 'minutes mom action items agenda', ready: true },
  { id: 'presentation-generator', name: 'Presentation generator', desc: 'Turn a Markdown outline or notes into a .pptx deck with four themes and speaker notes. Claude can draft it.', icon: 'presentation', also: ['ai', 'student'], tags: 'ppt pptx slides deck text to presentation outline', ready: true },
  { id: 'invoice-generator', name: 'Invoice generator', desc: 'GST or simple invoices with CGST, SGST and IGST, amount in words, UPI QR and PDF download.', icon: 'receipt', also: ['india'], tags: 'invoice bill gst freelance hsn upi tax', ready: true },
  { id: 'email-signature', name: 'Email signature generator', desc: 'Design an email signature with a live preview and copy it as rich HTML for Gmail and Outlook.', icon: 'pen-tool', tags: 'signature gmail outlook html', ready: true },
  { id: 'business-card', name: 'Business card maker', desc: 'Design a front and back card with a vCard QR code, then print 10 per sheet or export PNG.', icon: 'contact', tags: 'visiting card print qr vcard', ready: true },
  { id: 'job-tracker', name: 'Job application tracker', desc: 'Track every application on a kanban board with follow-up reminders, a weekly goal and CSV export.', icon: 'kanban', also: ['personal'], tags: 'job search applications kanban tracker follow up offer interview', ready: true },
  { id: 'interview-prep', name: 'Interview prep', desc: 'Likely questions from your role and the job post, a STAR answer builder, a practice timer and AI coaching.', icon: 'messages-square', also: ['student'], tags: 'interview questions star practice behavioral prepare answers', ready: true },
]
