// Pack dev-format: formatters, validators, viewers and diffing. Default category: dev.
export const cat = 'dev'
export default [
  { id: 'json-formatter', name: 'JSON formatter', desc: 'Pretty-print, minify and fix JSON with syntax errors pointed out.', icon: 'braces', also: ['data'], tags: 'json pretty beautify format', ready: true },
  { id: 'json-validator', name: 'JSON validator', module: 'json-formatter', params: { mode: 'validate' }, desc: 'Validate JSON and see exactly where it breaks.', icon: 'circle-check', tags: 'json lint validate', ready: true },
  { id: 'json-tree-viewer', name: 'JSON tree viewer', desc: 'Explore large JSON as a collapsible tree with search and paths.', icon: 'list-tree', tags: 'json viewer explorer', ready: true },
  { id: 'json-diff', name: 'JSON diff', desc: 'Compare two JSON documents structurally, ignoring key order.', icon: 'git-compare', tags: 'json compare difference', ready: true },
  { id: 'json-schema-generator', name: 'JSON schema generator', desc: 'Infer a JSON Schema from sample JSON.', icon: 'file-json', tags: 'schema infer json', ready: true },
  { id: 'json-to-typescript', name: 'JSON to TypeScript', desc: 'Generate TypeScript interfaces from JSON.', icon: 'file-code', tags: 'typescript types interface', ready: true },
  { id: 'xml-formatter', name: 'XML formatter', desc: 'Pretty-print, minify and validate XML.', icon: 'code-xml', tags: 'xml pretty', ready: true },
  { id: 'yaml-formatter', name: 'YAML formatter', desc: 'Format and validate YAML.', icon: 'file-cog', tags: 'yaml yml lint', ready: true },
  { id: 'yaml-to-json', name: 'YAML to JSON', module: 'yaml-formatter', params: { convert: true }, desc: 'Convert YAML to JSON and JSON to YAML.', icon: 'arrow-left-right', tags: 'yaml json convert', ready: true },
  { id: 'html-formatter', name: 'HTML formatter', module: 'code-formatter', params: { lang: 'html' }, desc: 'Beautify messy HTML with Prettier.', icon: 'code', tags: 'html beautify prettier', ready: true },
  { id: 'css-formatter', name: 'CSS formatter', module: 'code-formatter', params: { lang: 'css' }, desc: 'Beautify CSS, SCSS and Less with Prettier.', icon: 'paintbrush', tags: 'css scss beautify', ready: true },
  { id: 'js-formatter', name: 'JavaScript formatter', module: 'code-formatter', params: { lang: 'js' }, desc: 'Beautify JavaScript and TypeScript with Prettier.', icon: 'file-code-2', tags: 'javascript typescript prettier', ready: true },
  { id: 'code-beautifier', name: 'Code beautifier', module: 'code-formatter', desc: 'Format JS, TS, JSON, CSS, HTML, Markdown, YAML and GraphQL.', icon: 'wand-sparkles', tags: 'beautify prettier format code', ready: true },
  { id: 'code-minifier', name: 'Code minifier', desc: 'Minify JavaScript, CSS, HTML and JSON.', icon: 'minimize', tags: 'minify compress terser', ready: true },
  { id: 'sql-formatter', name: 'SQL formatter', desc: 'Format SQL for MySQL, PostgreSQL, SQL Server, BigQuery and more.', icon: 'database', also: ['data'], tags: 'sql pretty format', ready: true },
  { id: 'sql-minifier', name: 'SQL minifier', module: 'sql-formatter', params: { minify: true }, desc: 'Collapse SQL to a single compact line.', icon: 'minimize', tags: 'sql minify', ready: true },
  { id: 'markdown-editor', name: 'Markdown editor', desc: 'Write Markdown with live preview; export HTML or PDF.', icon: 'file-pen', also: ['text'], tags: 'markdown md editor preview', ready: true },
  { id: 'markdown-to-html', name: 'Markdown to HTML', module: 'markdown-editor', params: { output: 'html' }, desc: 'Convert Markdown to clean HTML.', icon: 'file-code', tags: 'md html convert', ready: true },
  { id: 'diff-checker', name: 'Diff checker', desc: 'Compare two texts or files side by side with highlighted changes.', icon: 'diff', also: ['text', 'files'], tags: 'diff compare difference text files', ready: true },
  { id: 'html-entities', name: 'HTML entity encoder', desc: 'Encode and decode HTML entities like &amp; and &#x1F600;.', icon: 'ampersand', tags: 'html entities escape', ready: true },
  { id: 'string-escape', name: 'String escaper', desc: 'Escape and unescape strings for JSON, JavaScript, CSV, SQL and regex.', icon: 'quote', tags: 'escape unescape string', ready: true },
  { id: 'js-minifier', name: 'JavaScript minifier', module: 'code-minifier', params: { lang: 'js' }, desc: 'Minify and mangle JavaScript with Terser and see the size savings.', icon: 'minimize', tags: 'javascript minify uglify terser compress', ready: true },
  { id: 'css-minifier', name: 'CSS minifier', module: 'code-minifier', params: { lang: 'css' }, desc: 'Minify CSS and merge duplicate rules with csso.', icon: 'minimize', tags: 'css minify compress csso', ready: true },
  { id: 'html-minifier', name: 'HTML minifier', module: 'code-minifier', params: { lang: 'html' }, desc: 'Minify HTML, inline CSS and inline JavaScript.', icon: 'minimize', tags: 'html minify compress whitespace', ready: true },
  { id: 'json-minifier', name: 'JSON minifier', module: 'json-formatter', params: { mode: 'minify' }, desc: 'Strip whitespace from JSON and see how many bytes you save.', icon: 'minimize', tags: 'json minify compact compress', ready: true },
  { id: 'xml-validator', name: 'XML validator', module: 'xml-formatter', params: { mode: 'validate' }, desc: 'Check that XML is well-formed and find the exact line of any error.', icon: 'circle-check', tags: 'xml validate lint well-formed', ready: true },
  { id: 'yaml-validator', name: 'YAML validator', module: 'yaml-formatter', params: { validate: true }, desc: 'Check YAML syntax and see the line of any indentation or key error.', icon: 'circle-check', tags: 'yaml yml validate lint', ready: true },
  { id: 'typescript-formatter', name: 'TypeScript formatter', module: 'code-formatter', params: { lang: 'ts' }, desc: 'Beautify TypeScript and TSX with Prettier.', icon: 'file-code', tags: 'typescript tsx prettier format', ready: true },
  { id: 'graphql-formatter', name: 'GraphQL formatter', module: 'code-formatter', params: { lang: 'graphql' }, desc: 'Format GraphQL queries and schemas with Prettier.', icon: 'share-2', tags: 'graphql gql query schema prettier', ready: true },
  { id: 'markdown-formatter', name: 'Markdown formatter', module: 'code-formatter', params: { lang: 'markdown' }, desc: 'Tidy Markdown: align tables, normalise lists and wrap prose.', icon: 'file-text', tags: 'markdown md prettier format tables', ready: true },
]
