// Pack calc-time: date, time, age and unit converters. Default category: calc.
export const cat = 'calc'
export default [
  { id: 'age-calculator', name: 'Age calculator', desc: 'Exact age in years, months and days, on any date, plus next birthday.', icon: 'cake', also: ['personal'], tags: 'age birthday exact dob', ready: true },
  { id: 'date-difference', name: 'How many days between dates', desc: 'Days, weeks, months and years between two dates.', icon: 'calendar-range', tags: 'days between dates difference', ready: true },
  { id: 'add-days-to-date', name: 'Date + N days', desc: 'Add or subtract days, weeks, months or business days from a date.', icon: 'calendar-plus', tags: 'add subtract date', ready: true },
  { id: 'working-days', name: 'Working days calculator', desc: 'Business days between dates, excluding weekends and holidays.', icon: 'briefcase', also: ['career'], tags: 'business days weekdays holidays', ready: true },
  { id: 'business-days-india', name: 'Business days (Indian holidays)', module: 'working-days', params: { holidays: 'in' }, cat: 'india', desc: 'Working days between dates excluding Indian public holidays.', icon: 'calendar-check', tags: 'india holidays gazetted bank', ready: true },
  { id: 'time-difference', name: 'Time & duration calculator', desc: 'Hours between times, add up durations, and convert time units.', icon: 'clock', tags: 'hours minutes duration add time', ready: true },
  { id: 'time-zone-converter', name: 'Time zone converter', desc: 'Convert a time between cities and time zones (IST, PST, GMT...).', icon: 'globe', tags: 'timezone ist utc gmt', ready: true },
  { id: 'meeting-planner', name: 'Meeting time planner', desc: 'Find overlapping working hours across time zones.', icon: 'users', also: ['career'], tags: 'time zone overlap meeting', ready: true },
  { id: 'countdown-generator', name: 'Countdown generator', desc: 'Create a shareable countdown link to any date and time.', icon: 'hourglass', also: ['personal'], tags: 'countdown event timer link', ready: true },
  { id: 'unit-converter', name: 'Unit converter', desc: 'Convert length, weight, temperature, area, volume, speed and more.', icon: 'arrow-left-right', tags: 'convert units metric imperial', ready: true },
  { id: 'length-converter', name: 'Length converter', module: 'unit-converter', params: { kind: 'length' }, desc: 'km, m, cm, mm, miles, feet, inches and more.', icon: 'ruler', tags: 'feet inches meters', ready: true },
  { id: 'weight-converter', name: 'Weight converter', module: 'unit-converter', params: { kind: 'weight' }, desc: 'kg, g, lb, oz, tonnes and more.', icon: 'weight', tags: 'kg lbs pounds', ready: true },
  { id: 'temperature-converter', name: 'Temperature converter', module: 'unit-converter', params: { kind: 'temperature' }, desc: 'Celsius, Fahrenheit and Kelvin.', icon: 'thermometer', tags: 'celsius fahrenheit', ready: true },
  { id: 'area-converter', name: 'Area converter', module: 'unit-converter', params: { kind: 'area' }, desc: 'sq ft, sq m, acres, hectares, bigha, guntha and more.', icon: 'square-dashed', tags: 'sqft acre hectare bigha', ready: true },
  { id: 'volume-converter', name: 'Volume converter', module: 'unit-converter', params: { kind: 'volume' }, desc: 'Litres, ml, gallons, cups, cubic meters and more.', icon: 'cylinder', tags: 'litre gallon cup', ready: true },
  { id: 'speed-converter', name: 'Speed converter', module: 'unit-converter', params: { kind: 'speed' }, desc: 'km/h, mph, m/s and knots.', icon: 'gauge', tags: 'kmh mph', ready: true },
  { id: 'data-storage-converter', name: 'Data storage converter', module: 'unit-converter', params: { kind: 'data' }, desc: 'Bytes, KB, MB, GB, TB (decimal and binary).', icon: 'hard-drive', also: ['dev'], tags: 'mb gb kb bytes mib', ready: true },
  { id: 'pressure-converter', name: 'Pressure converter', module: 'unit-converter', params: { kind: 'pressure' }, desc: 'psi, bar, kPa, atm, mmHg and kgf/cm2.', icon: 'gauge', tags: 'psi bar pascal tyre pressure', ready: true },
  { id: 'energy-converter', name: 'Energy converter', module: 'unit-converter', params: { kind: 'energy' }, desc: 'Joules, calories, kWh (units of electricity), BTU and more.', icon: 'zap', tags: 'kwh calorie joule btu', ready: true },
  { id: 'power-converter', name: 'Power converter', module: 'unit-converter', params: { kind: 'power' }, desc: 'Watts, kW, horsepower, BTU/h and AC tons.', icon: 'plug-zap', tags: 'hp kw watt ton ac', ready: true },
  { id: 'fuel-economy-converter', name: 'Fuel economy converter', module: 'unit-converter', params: { kind: 'fuel' }, desc: 'km/L, L/100 km and miles per gallon.', icon: 'fuel', tags: 'mileage mpg kmpl', ready: true },
  { id: 'time-unit-converter', name: 'Time unit converter', module: 'unit-converter', params: { kind: 'time' }, desc: 'Seconds, minutes, hours, days, weeks, months and years.', icon: 'clock', tags: 'seconds hours days convert', ready: true },
  { id: 'cooking-converter', name: 'Cooking converter', module: 'unit-converter', params: { kind: 'cooking' }, desc: 'Cups, spoons, grams and ounces for flour, sugar, butter and more.', icon: 'chef-hat', also: ['personal'], tags: 'cup tbsp tsp grams baking recipe', ready: true },
  { id: 'land-area-india', name: 'Land area converter (India)', module: 'unit-converter', params: { kind: 'area', india: true }, cat: 'india', desc: 'Bigha, biswa, guntha, kanal, marla, cent and gaj to sq ft and acres.', icon: 'map', tags: 'bigha guntha kanal marla cent gaj land plot', ready: true },
  { id: 'number-to-words', name: 'Number to words', desc: 'Write numbers in words (international and Indian lakh/crore).', icon: 'whole-word', also: ['india'], tags: 'amount in words cheque lakh crore', ready: true },
  { id: 'roman-numerals', name: 'Roman numeral converter', desc: 'Convert numbers to Roman numerals and back.', icon: 'type', tags: 'roman numerals', ready: true },
  { id: 'day-of-week', name: 'Day of the week calculator', desc: 'Find the weekday of any date, with day of year, leap year and the same date in other years.', icon: 'calendar-search', tags: 'weekday what day was birthday', ready: true },
  { id: 'week-number', name: 'Week number', desc: 'ISO week number of any date and the dates in any week.', icon: 'calendar-days', tags: 'iso week', ready: true },
]
