// Pack image-edit: everyday image editing and conversion. Default category: image.
export const cat = 'image'
export default [
  { id: 'resize-image', name: 'Resize image', desc: 'Resize by pixels, percent or print size, one image or a whole batch.', icon: 'scaling', tags: 'resize scale dimensions batch bulk' },
  { id: 'batch-image-resizer', name: 'Batch image resizer', module: 'resize-image', params: { batch: true }, desc: 'Resize many images at once and download them as a ZIP.', icon: 'images', tags: 'bulk multiple resize zip' },
  { id: 'exact-size-image', name: 'Make image exactly X x Y px', module: 'resize-image', params: { exact: true }, desc: 'Get an exact pixel size by cropping, padding or stretching.', icon: 'frame', tags: 'exact dimensions pixels fit fill' },
  { id: 'compress-image', name: 'Compress image', desc: 'Shrink JPG, PNG and WebP files with a quality slider and live preview.', icon: 'minimize-2', tags: 'reduce size optimize smaller' },
  { id: 'image-to-kb', name: 'Image to exact KB', desc: 'Type a size like 20 KB and get the best quality that fits.', icon: 'target', also: ['india', 'files'], tags: 'kb size limit target form upload reduce 20kb 50kb 100kb' },
  { id: 'crop-image', name: 'Crop image', desc: 'Crop freely or to ratios like 1:1, 4:5, 16:9 and passport sizes.', icon: 'crop', tags: 'cut trim aspect ratio' },
  { id: 'rotate-image', name: 'Rotate & flip image', desc: 'Rotate by any angle and flip horizontally or vertically.', icon: 'rotate-cw', tags: 'turn mirror flip' },
  { id: 'image-converter', name: 'Image converter', module: 'convert-image', desc: 'Convert between JPG, PNG, WebP, AVIF, GIF, BMP and ICO.', icon: 'repeat-2', tags: 'convert format' },
  { id: 'jpg-to-png', name: 'JPG to PNG', module: 'convert-image', params: { from: 'jpg', to: 'png' }, desc: 'Convert JPG photos to lossless PNG.', icon: 'file-image', tags: 'jpeg png convert' },
  { id: 'png-to-jpg', name: 'PNG to JPG', module: 'convert-image', params: { from: 'png', to: 'jpg' }, desc: 'Convert PNG to smaller JPG with a background color for transparency.', icon: 'file-image', tags: 'png jpeg convert' },
  { id: 'jpg-to-webp', name: 'JPG to WebP', module: 'convert-image', params: { from: 'jpg', to: 'webp' }, desc: 'Convert JPG to modern, smaller WebP.', icon: 'file-image', tags: 'webp convert' },
  { id: 'png-to-webp', name: 'PNG to WebP', module: 'convert-image', params: { from: 'png', to: 'webp' }, desc: 'Convert PNG to WebP while keeping transparency.', icon: 'file-image', tags: 'webp convert' },
  { id: 'webp-to-jpg', name: 'WebP to JPG', module: 'convert-image', params: { from: 'webp', to: 'jpg' }, desc: 'Convert WebP images to widely supported JPG.', icon: 'file-image', tags: 'webp jpeg convert' },
  { id: 'webp-to-png', name: 'WebP to PNG', module: 'convert-image', params: { from: 'webp', to: 'png' }, desc: 'Convert WebP images to PNG.', icon: 'file-image', tags: 'webp png convert' },
  { id: 'heic-to-jpg', name: 'HEIC to JPG', desc: 'Convert iPhone HEIC/HEIF photos to JPG or PNG, in bulk.', icon: 'smartphone', tags: 'iphone heif apple convert' },
  { id: 'svg-to-png', name: 'SVG to PNG', desc: 'Render SVG vector files to PNG at any size.', icon: 'pen-tool', also: ['dev'], tags: 'vector rasterize' },
  { id: 'add-text-to-image', name: 'Add text to image', desc: 'Place styled text, captions and labels on a photo.', icon: 'type', tags: 'caption label text overlay' },
  { id: 'watermark-image', name: 'Watermark image', desc: 'Add a text or logo watermark to one or many images.', icon: 'stamp', tags: 'logo copyright brand' },
  { id: 'blur-image', name: 'Blur sensitive info', desc: 'Blur or pixelate faces, numbers and private details in screenshots.', icon: 'eye-off', also: ['security'], tags: 'pixelate redact censor hide' },
  { id: 'image-filters', name: 'Adjust & filter image', desc: 'Brightness, contrast, saturation, warmth, grayscale, sepia and more.', icon: 'sliders-horizontal', tags: 'edit adjust filter grayscale sepia' },
  { id: 'invert-image', name: 'Image negative', module: 'image-filters', params: { preset: 'invert' }, desc: 'Invert the colors of an image to make a negative.', icon: 'contrast', tags: 'invert negative' },
  { id: 'circle-crop', name: 'Circle crop & round corners', desc: 'Make round profile pictures or rounded-corner images with transparency.', icon: 'circle', tags: 'profile picture avatar round' },
  { id: 'image-dpi', name: 'Change image DPI', desc: 'Set 72, 150, 300 or any DPI in JPG/PNG metadata without resampling.', icon: 'printer', tags: 'dpi ppi print resolution' },
  { id: 'image-info', name: 'Image resolution checker', desc: 'Dimensions, DPI, megapixels, file size and print sizes of any image.', icon: 'info', tags: 'resolution dimensions dpi size' },
  { id: 'exif-remover', name: 'EXIF metadata remover', desc: 'View and strip GPS location, camera and date info from photos.', icon: 'shield-off', also: ['security'], tags: 'exif gps location privacy metadata' },
  { id: 'image-to-base64', name: 'Image to Base64', desc: 'Encode an image as a Base64 data URI for HTML/CSS.', icon: 'file-code', also: ['dev'], tags: 'data uri base64 encode' },
  { id: 'base64-to-image', name: 'Base64 to image', desc: 'Decode a Base64 string or data URI back into an image file.', icon: 'image-down', also: ['dev'], tags: 'decode data uri' },
  { id: 'favicon-generator', name: 'Favicon generator', desc: 'Make favicon.ico and app icons in every size from one image.', icon: 'app-window', also: ['dev', 'web'], tags: 'ico icon website apple touch' },
]
