// Pack image-edit: everyday image editing and conversion. Default category: image.
export const cat = 'image'
export default [
  { id: 'resize-image', name: 'Resize image', desc: 'Resize by pixels, percent or print size, one image or a whole batch.', icon: 'scaling', tags: 'resize scale dimensions batch bulk', ready: true },
  { id: 'batch-image-resizer', name: 'Batch image resizer', module: 'resize-image', params: { batch: true }, desc: 'Resize many images at once and download them as a ZIP.', icon: 'images', tags: 'bulk multiple resize zip', ready: true },
  { id: 'exact-size-image', name: 'Make image exactly X x Y px', module: 'resize-image', params: { exact: true }, desc: 'Get an exact pixel size by cropping, padding or stretching.', icon: 'frame', tags: 'exact dimensions pixels fit fill', ready: true },
  { id: 'compress-image', name: 'Compress image', desc: 'Shrink JPG, PNG and WebP files with a quality slider and live preview.', icon: 'minimize-2', tags: 'reduce size optimize smaller', ready: true },
  { id: 'image-to-kb', name: 'Image to exact KB', desc: 'Type a size like 20 KB and get the best quality that fits.', icon: 'target', also: ['india', 'files'], tags: 'kb size limit target form upload reduce 20kb 50kb 100kb', ready: true },
  { id: 'crop-image', name: 'Crop image', desc: 'Crop freely or to ratios like 1:1, 4:5, 16:9 and passport sizes.', icon: 'crop', tags: 'cut trim aspect ratio', ready: true },
  { id: 'rotate-image', name: 'Rotate & flip image', desc: 'Rotate by any angle and flip horizontally or vertically.', icon: 'rotate-cw', tags: 'turn mirror flip', ready: true },
  { id: 'flip-image', name: 'Flip & mirror image', module: 'rotate-image', params: { mode: 'flip' }, desc: 'Mirror a photo left to right or flip it upside down.', icon: 'flip-horizontal-2', tags: 'mirror flip horizontal vertical reverse', ready: true },
  { id: 'image-converter', name: 'Image converter', module: 'convert-image', desc: 'Convert between JPG, PNG, WebP, AVIF, GIF, BMP and ICO.', icon: 'repeat-2', tags: 'convert format', ready: true },
  { id: 'jpg-to-png', name: 'JPG to PNG', module: 'convert-image', params: { from: 'jpg', to: 'png' }, desc: 'Convert JPG photos to lossless PNG.', icon: 'file-image', tags: 'jpeg png convert', ready: true },
  { id: 'png-to-jpg', name: 'PNG to JPG', module: 'convert-image', params: { from: 'png', to: 'jpg' }, desc: 'Convert PNG to smaller JPG with a background color for transparency.', icon: 'file-image', tags: 'png jpeg convert', ready: true },
  { id: 'jpg-to-webp', name: 'JPG to WebP', module: 'convert-image', params: { from: 'jpg', to: 'webp' }, desc: 'Convert JPG to modern, smaller WebP.', icon: 'file-image', tags: 'webp convert', ready: true },
  { id: 'png-to-webp', name: 'PNG to WebP', module: 'convert-image', params: { from: 'png', to: 'webp' }, desc: 'Convert PNG to WebP while keeping transparency.', icon: 'file-image', tags: 'webp convert', ready: true },
  { id: 'webp-to-jpg', name: 'WebP to JPG', module: 'convert-image', params: { from: 'webp', to: 'jpg' }, desc: 'Convert WebP images to widely supported JPG.', icon: 'file-image', tags: 'webp jpeg convert', ready: true },
  { id: 'webp-to-png', name: 'WebP to PNG', module: 'convert-image', params: { from: 'webp', to: 'png' }, desc: 'Convert WebP images to PNG.', icon: 'file-image', tags: 'webp png convert', ready: true },
  { id: 'png-to-ico', name: 'PNG to ICO', module: 'convert-image', params: { from: 'png', to: 'ico' }, desc: 'Turn a PNG into a Windows icon with several sizes inside.', icon: 'app-window', also: ['dev', 'web'], tags: 'ico icon favicon windows convert', ready: true },
  { id: 'avif-to-jpg', name: 'AVIF to JPG', module: 'convert-image', params: { from: 'avif', to: 'jpg' }, desc: 'Convert AVIF images to widely supported JPG.', icon: 'file-image', tags: 'avif jpeg convert', ready: true },
  { id: 'gif-to-png', name: 'GIF to PNG', module: 'convert-image', params: { from: 'gif', to: 'png' }, desc: 'Convert GIF images to PNG. Animated GIFs use their first frame.', icon: 'file-image', tags: 'gif png convert frame', ready: true },
  { id: 'heic-to-jpg', name: 'HEIC to JPG', desc: 'Convert iPhone HEIC/HEIF photos to JPG or PNG, in bulk.', icon: 'smartphone', tags: 'iphone heif apple convert', ready: true },
  { id: 'svg-to-png', name: 'SVG to PNG', desc: 'Render SVG vector files to PNG at any size.', icon: 'pen-tool', also: ['dev'], tags: 'vector rasterize', ready: true },
  { id: 'add-text-to-image', name: 'Add text to image', desc: 'Place styled text, captions and labels on a photo.', icon: 'type', tags: 'caption label text overlay', ready: true },
  { id: 'watermark-image', name: 'Watermark image', desc: 'Add a text or logo watermark to one or many images.', icon: 'stamp', tags: 'logo copyright brand', ready: true },
  { id: 'blur-image', name: 'Blur sensitive info', desc: 'Blur or pixelate faces, numbers and private details in screenshots.', icon: 'eye-off', also: ['security'], tags: 'pixelate redact censor hide', ready: true },
  { id: 'pixelate-image', name: 'Pixelate image', module: 'blur-image', params: { mode: 'pixelate' }, desc: 'Pixelate faces, plates and private details with mosaic blocks.', icon: 'grid-3x3', also: ['security'], tags: 'mosaic censor pixelate hide', ready: true },
  { id: 'image-filters', name: 'Adjust & filter image', desc: 'Brightness, contrast, saturation, warmth, grayscale, sepia and more.', icon: 'sliders-horizontal', tags: 'edit adjust filter grayscale sepia', ready: true },
  { id: 'invert-image', name: 'Image negative', module: 'image-filters', params: { preset: 'invert' }, desc: 'Invert the colors of an image to make a negative.', icon: 'contrast', tags: 'invert negative', ready: true },
  { id: 'black-and-white-image', name: 'Black & white photo', module: 'image-filters', params: { preset: 'bw' }, desc: 'Turn a color photo into black and white with adjustable contrast.', icon: 'blend', tags: 'grayscale monochrome greyscale bw noir', ready: true },
  { id: 'circle-crop', name: 'Circle crop & round corners', desc: 'Make round profile pictures or rounded-corner images with transparency.', icon: 'circle', tags: 'profile picture avatar round', ready: true },
  { id: 'round-corners-image', name: 'Round image corners', module: 'circle-crop', params: { shape: 'corners' }, desc: 'Round the corners of any image and save it as a transparent PNG.', icon: 'square-round-corner', tags: 'rounded corners radius transparent', ready: true },
  { id: 'image-dpi', name: 'Change image DPI', desc: 'Set 72, 150, 300 or any DPI in JPG/PNG metadata without resampling.', icon: 'printer', tags: 'dpi ppi print resolution', ready: true },
  { id: 'image-info', name: 'Image resolution checker', desc: 'Dimensions, DPI, megapixels, file size and print sizes of any image.', icon: 'info', tags: 'resolution dimensions dpi size', ready: true },
  { id: 'exif-remover', name: 'EXIF metadata remover', desc: 'View and strip GPS location, camera and date info from photos.', icon: 'shield-off', also: ['security'], tags: 'exif gps location privacy metadata', ready: true },
  { id: 'exif-viewer', name: 'EXIF viewer', module: 'exif-remover', params: { view: true }, desc: 'See the camera, date and GPS location hidden inside any photo.', icon: 'scan-search', also: ['security'], tags: 'exif viewer metadata gps location camera lens', ready: true },
  { id: 'image-to-base64', name: 'Image to Base64', desc: 'Encode an image as a Base64 data URI for HTML/CSS.', icon: 'file-code', also: ['dev'], tags: 'data uri base64 encode', ready: true },
  { id: 'base64-to-image', name: 'Base64 to image', desc: 'Decode a Base64 string or data URI back into an image file.', icon: 'image-down', also: ['dev'], tags: 'decode data uri', ready: true },
  { id: 'favicon-generator', name: 'Favicon generator', desc: 'Make favicon.ico and app icons in every size from one image.', icon: 'app-window', also: ['dev', 'web'], tags: 'ico icon website apple touch', ready: true },
]
