// Pack web: QR codes, links, websites and network lookups. Default category: web.
export const cat = 'web'
export default [
  { ready: true, id: 'qr-generator', name: 'QR code generator', desc: 'QR codes for links, text, email, SMS and more, with colors and logo.', icon: 'qr-code', also: ['security'], tags: 'qr code generate' },
  { ready: true, id: 'wifi-qr', name: 'Wi-Fi QR code', module: 'qr-generator', params: { type: 'wifi' }, desc: 'Let guests join your Wi-Fi by scanning a QR code.', icon: 'wifi', also: ['security'], tags: 'wifi password qr' },
  { ready: true, id: 'vcard-qr', name: 'vCard QR code', module: 'qr-generator', params: { type: 'vcard' }, desc: 'Share your contact card as a scannable QR code.', icon: 'contact', tags: 'contact vcard qr' },
  { ready: true, id: 'upi-qr', name: 'UPI payment QR', module: 'qr-generator', params: { type: 'upi' }, cat: 'india', desc: 'Make a UPI QR with your UPI ID, name and amount for GPay, PhonePe, Paytm.', icon: 'indian-rupee', tags: 'upi gpay phonepe paytm payment' },
  { ready: true, id: 'whatsapp-link-generator', name: 'WhatsApp link and QR', module: 'qr-generator', params: { type: 'whatsapp' }, desc: 'Make a click-to-chat link and QR code for a WhatsApp number, with an optional message.', icon: 'message-circle', tags: 'wa.me whatsapp chat link number' },
  { ready: true, id: 'qr-scanner', name: 'QR code scanner', desc: 'Scan QR codes and barcodes with your camera or from an image.', icon: 'scan-qr-code', also: ['security'], tags: 'scan read qr barcode' },
  { ready: true, id: 'barcode-generator', name: 'Barcode generator', desc: 'Code 128, EAN-13, UPC, Code 39 and more as PNG or SVG.', icon: 'barcode', tags: 'barcode ean upc code128' },
  { ready: true, id: 'url-shortener', name: 'URL shortener', desc: 'Shorten long links in one click.', icon: 'link-2', mode: 'online', tags: 'short link tinyurl' },
  { id: 'website-screenshot', name: 'Website screenshot', desc: 'Capture a screenshot of any web page by URL.', icon: 'camera', mode: 'online', tags: 'screenshot capture url' },
  { id: 'full-page-screenshot', name: 'Full-page screenshot', module: 'website-screenshot', params: { full: true }, desc: 'Capture the entire scrolling page as one tall image.', icon: 'scroll', mode: 'online', tags: 'full page long screenshot' },
  { id: 'webpage-to-pdf', name: 'Webpage to PDF', desc: 'Save any web page as a PDF by URL.', icon: 'file-down', mode: 'online', also: ['pdf'], tags: 'url pdf save page' },
  { ready: true, id: 'website-to-text', name: 'Website to text', desc: 'Get the readable text (or Markdown) of any web page.', icon: 'file-text', mode: 'online', tags: 'scrape extract article reader' },
  { ready: true, id: 'html-to-markdown', name: 'HTML to Markdown', desc: 'Convert HTML to clean Markdown.', icon: 'file-code', also: ['dev'], tags: 'html md convert' },
  { id: 'url-metadata', name: 'URL metadata & link preview', desc: 'See title, description, Open Graph and Twitter card for a link.', icon: 'tags', mode: 'online', tags: 'og open graph meta preview seo' },
  { ready: true, id: 'uptime-checker', name: 'Website uptime checker', desc: 'Check if a site responds and how fast, and keep watching while this tab is open.', icon: 'activity', mode: 'online', tags: 'down is it down status monitor' },
  { ready: true, id: 'dns-lookup', name: 'DNS lookup', desc: 'A, AAAA, MX, TXT, CNAME, NS records via DNS-over-HTTPS.', icon: 'server', mode: 'online', also: ['dev'], tags: 'dns mx txt records' },
  { ready: true, id: 'ip-lookup', name: 'IP address lookup', desc: 'Your public IP, or location and ISP for any IP address.', icon: 'map-pin', mode: 'online', tags: 'ip whois location isp my ip' },
  { ready: true, id: 'my-ip', name: 'What is my IP address', module: 'ip-lookup', params: { focus: 'me' }, desc: 'See your public IP address, location and internet provider in one click.', icon: 'locate-fixed', mode: 'online', tags: 'my ip public address what is' },
  { ready: true, id: 'http-headers', name: 'HTTP header checker', desc: 'See the response headers and status a URL returns.', icon: 'list', mode: 'online', also: ['dev'], tags: 'headers status response' },
  { ready: true, id: 'ssl-checker', name: 'SSL certificate checker', desc: 'Certificate issuer, validity dates and history for a domain from public CT logs.', icon: 'shield-check', mode: 'online', also: ['security'], tags: 'ssl tls https certificate expiry' },
  { ready: true, id: 'domain-availability', name: 'Domain availability checker', desc: 'Check if a domain is registered and see its registration data.', icon: 'globe', mode: 'online', tags: 'domain whois rdap available' },
  { ready: true, id: 'whois-lookup', name: 'WHOIS domain lookup', module: 'domain-availability', params: { mode: 'whois' }, desc: 'Registrar, registration and expiry dates, status and nameservers for any domain.', icon: 'scan-search', mode: 'online', tags: 'whois rdap registrar expiry domain age owner' },
  { ready: true, id: 'sitemap-generator', name: 'Sitemap generator', desc: 'Build a sitemap.xml from a list of URLs or the links found on a page.', icon: 'network', also: ['dev'], tags: 'sitemap xml seo' },
  { ready: true, id: 'url-parser', name: 'URL parser', desc: 'Break a URL into protocol, host, path, query and hash.', icon: 'link', also: ['dev'], tags: 'url parse components' },
  { ready: true, id: 'query-string-parser', name: 'Query string parser', module: 'url-parser', params: { focus: 'query' }, desc: 'Decode and edit URL query parameters as a table.', icon: 'list-tree', also: ['dev'], tags: 'query params utm' },
  { ready: true, id: 'utm-builder', name: 'UTM link builder', desc: 'Add UTM campaign tags to links for analytics.', icon: 'megaphone', tags: 'utm campaign analytics marketing' },
  { ready: true, id: 'meta-tag-generator', name: 'Meta tag generator', desc: 'Generate SEO, Open Graph and Twitter meta tags for a page.', icon: 'code', also: ['dev'], tags: 'seo meta og tags' },
  { ready: true, id: 'robots-txt', name: 'robots.txt generator', desc: 'Build a robots.txt with allow/disallow rules and sitemap.', icon: 'bot', also: ['dev'], tags: 'robots crawler seo' },
  { ready: true, id: 'internet-speed-test', name: 'Internet speed test', desc: 'Measure download, upload and latency from your browser.', icon: 'gauge', mode: 'online', tags: 'speed test bandwidth ping' },
  { ready: true, id: 'browser-info', name: 'What is my browser', desc: 'Browser, OS, screen, language and feature support at a glance.', icon: 'monitor-smartphone', also: ['dev', 'screen'], tags: 'user agent screen resolution' },
]
