// Pack text-utils: tiny text tools people search for ("I need to do one specific thing"). Default category: text.
// Many entries share one module with different params so each tool page is focused.
export const cat = 'text'
export default [
  { id: 'word-counter', name: 'Word counter', desc: 'Count words, characters, sentences, paragraphs and reading time.', icon: 'whole-word', tags: 'count words characters reading time', ready: true },
  { id: 'character-counter', name: 'Character counter', module: 'word-counter', params: { focus: 'chars' }, desc: 'Count characters with and without spaces, with tweet/SMS limits.', icon: 'type', tags: 'letters length limit twitter sms', ready: true },
  { id: 'line-counter', name: 'Count lines', module: 'word-counter', params: { focus: 'lines' }, desc: 'Count total, non-empty and unique lines.', icon: 'list', tags: 'lines count', ready: true },
  { id: 'word-frequency', name: 'Word frequency counter', desc: 'See the most used words and phrases in any text.', icon: 'chart-bar', tags: 'keyword density frequency' },
  { id: 'case-converter', name: 'Case converter', desc: 'UPPER, lower, Title, Sentence, camelCase, snake_case, kebab-case and more.', icon: 'case-sensitive', tags: 'uppercase lowercase title camel snake' },
  { id: 'remove-duplicate-lines', name: 'Remove duplicate lines', module: 'line-tools', params: { op: 'dedupe' }, desc: 'Delete repeated lines, keeping the first occurrence.', icon: 'list-x', tags: 'unique dedupe duplicates' },
  { id: 'remove-empty-lines', name: 'Remove empty lines', module: 'line-tools', params: { op: 'remove-empty' }, desc: 'Strip blank lines from text.', icon: 'list-minus', tags: 'blank lines' },
  { id: 'sort-lines', name: 'Sort lines', module: 'line-tools', params: { op: 'sort' }, desc: 'Sort lines A-Z, Z-A, by length, numerically or randomly.', icon: 'arrow-down-a-z', tags: 'alphabetical order shuffle' },
  { id: 'reverse-text', name: 'Reverse text', module: 'line-tools', params: { op: 'reverse' }, desc: 'Reverse characters, words or line order.', icon: 'flip-horizontal', tags: 'backwards mirror' },
  { id: 'add-line-prefix', name: 'Add prefix to every line', module: 'line-tools', params: { op: 'prefix' }, desc: 'Put the same text at the start of every line.', icon: 'list-plus', tags: 'prepend bullet' },
  { id: 'add-line-suffix', name: 'Add suffix to every line', module: 'line-tools', params: { op: 'suffix' }, desc: 'Put the same text at the end of every line.', icon: 'list-end', tags: 'append comma' },
  { id: 'number-lines', name: 'Number every line', module: 'line-tools', params: { op: 'number' }, desc: 'Add 1., 2., 3. (or any format) to each line.', icon: 'list-ordered', tags: 'numbering' },
  { id: 'remove-line-numbers', name: 'Remove line numbers', module: 'line-tools', params: { op: 'unnumber' }, desc: 'Strip leading numbers, bullets and markers from lines.', icon: 'list', tags: 'strip numbers bullets' },
  { id: 'join-lines', name: 'Join or split lines', module: 'line-tools', params: { op: 'join' }, desc: 'Join lines with a separator, or split text into lines.', icon: 'wrap-text', tags: 'comma separated split delimiter' },
  { id: 'spaces-to-tabs', name: 'Spaces to tabs', module: 'line-tools', params: { op: 'spaces-to-tabs' }, desc: 'Convert runs of spaces into tabs.', icon: 'arrow-right-to-line', tags: 'indent tabs' },
  { id: 'tabs-to-spaces', name: 'Tabs to spaces', module: 'line-tools', params: { op: 'tabs-to-spaces' }, desc: 'Convert tabs into a chosen number of spaces.', icon: 'arrow-left-to-line', tags: 'indent spaces' },
  { id: 'remove-whitespace', name: 'Remove whitespace', module: 'line-tools', params: { op: 'remove-whitespace' }, desc: 'Trim, collapse or remove all spaces and line breaks.', icon: 'space', tags: 'trim spaces strip' },
  { id: 'normalize-whitespace', name: 'Normalize whitespace', module: 'line-tools', params: { op: 'normalize' }, desc: 'Fix double spaces, odd line breaks and invisible characters.', icon: 'align-left', tags: 'clean spaces tidy' },
  { id: 'clean-text', name: 'Clipboard text cleaner', desc: 'Paste messy text and clean it: smart quotes, line breaks, spaces, emojis.', icon: 'sparkles', also: ['screen'], tags: 'clean paste formatter tidy clipboard' },
  { id: 'find-replace', name: 'Find & replace', desc: 'Find and replace text, with case, whole-word and regex options.', icon: 'replace', tags: 'search substitute regex' },
  { id: 'extract-emails', name: 'Extract emails', module: 'extractor', params: { kind: 'emails' }, desc: 'Pull every email address out of any text.', icon: 'mail', tags: 'email addresses scrape' },
  { id: 'extract-phone-numbers', name: 'Extract phone numbers', module: 'extractor', params: { kind: 'phones' }, desc: 'Find phone numbers in text (Indian and international formats).', icon: 'phone', tags: 'mobile numbers' },
  { id: 'extract-urls', name: 'Extract URLs', module: 'extractor', params: { kind: 'urls' }, desc: 'List every link in a block of text.', icon: 'link-2', tags: 'links' },
  { id: 'extract-hashtags', name: 'Extract hashtags & mentions', module: 'extractor', params: { kind: 'hashtags' }, desc: 'Collect #hashtags and @mentions from posts.', icon: 'hash', tags: 'social media' },
  { id: 'extract-numbers', name: 'Extract numbers', module: 'extractor', params: { kind: 'numbers' }, desc: 'Pull out all numbers and get their sum and average.', icon: 'sigma', tags: 'digits amounts' },
  { id: 'extract-between', name: 'Extract text between brackets', module: 'extractor', params: { kind: 'between' }, desc: 'Get text between (), [], {}, quotes or any custom delimiters.', icon: 'brackets', tags: 'parentheses quotes delimiters' },
  { id: 'compare-lists', name: 'Compare two lists', module: 'list-compare', params: { op: 'diff' }, desc: 'Find items only in list A, only in B, and in both.', icon: 'git-compare-arrows', tags: 'difference diff' },
  { id: 'intersect-lists', name: 'Intersect two lists', module: 'list-compare', params: { op: 'intersect' }, desc: 'Keep only the items that appear in both lists.', icon: 'combine', tags: 'common intersection' },
  { id: 'union-lists', name: 'Union of two lists', module: 'list-compare', params: { op: 'union' }, desc: 'Merge two lists into one without duplicates.', icon: 'merge', tags: 'merge combine unique' },
  { id: 'subtract-lists', name: 'Remove list B from list A', module: 'list-compare', params: { op: 'subtract' }, desc: 'Remove items from list A that exist in list B.', icon: 'circle-minus', tags: 'minus exclude subtract' },
  { id: 'text-binary-hex', name: 'Text, binary & hex converter', desc: 'Convert text to binary, hex, octal, decimal or ASCII codes and back.', icon: 'binary', also: ['dev'], tags: 'binary hex ascii bytes' },
  { id: 'slugify', name: 'Text to URL slug', desc: 'Turn titles or filenames into clean-url-slugs.', icon: 'link', also: ['files', 'web'], tags: 'slug url filename seo' },
  { id: 'lorem-ipsum', name: 'Lorem ipsum generator', desc: 'Generate placeholder paragraphs, sentences or words.', icon: 'pilcrow', also: ['dev'], tags: 'dummy placeholder filler' },
  { id: 'fancy-text', name: 'Fancy text generator', desc: 'Bold, italic, script and other Unicode styles for bios and posts.', icon: 'sparkle', tags: 'unicode fonts instagram bio' },
  { id: 'morse-code', name: 'Morse code translator', desc: 'Translate text to Morse code and back, with audio playback.', icon: 'radio', tags: 'morse dots dashes' },
  { id: 'text-repeater', name: 'Text repeater', desc: 'Repeat a word or line N times with any separator.', icon: 'repeat', tags: 'repeat duplicate' },
]
