// Pack corel: CorelDRAW file tools (convert to CorelDRAW-ready vectors, open and edit .cdr). Default category: studio.
export const cat = 'studio'
export default [
  { id: 'convert-to-coreldraw', name: 'Convert to CorelDRAW format', desc: 'Turn PDF, SVG, PNG or JPG into CorelDRAW-ready EPS, AI, PDF or SVG, tracing photos and logos into vectors.', icon: 'file-output', also: ['image', 'pdf'], tags: 'corel coreldraw cdr eps ai convert vector trace png to cdr pdf to cdr svg to cdr jpg to cdr image to vector', ready: true },
  { id: 'cdr-viewer', name: 'CorelDRAW (CDR) viewer & editor', desc: 'Open .cdr files in your browser, see every page, edit them and save CorelDRAW-ready EPS, SVG or PDF.', icon: 'pen-tool', layout: 'app', also: ['image'], tags: 'corel coreldraw cdr open view edit cdr viewer cdr editor cdr reader', ready: true },
  { id: 'cdr-to-svg', name: 'CDR to SVG', desc: 'Open a CorelDRAW file and save it as clean SVG. Runs in your browser, nothing is uploaded.', icon: 'file-code', module: 'cdr-viewer', params: { to: 'svg' }, layout: 'app', also: ['image'], tags: 'cdr to svg corel coreldraw convert vector open cdr online', ready: true },
  { id: 'cdr-to-pdf', name: 'CDR to PDF', desc: 'Open a CorelDRAW file and save every page as a vector PDF, right in your browser.', icon: 'file-text', module: 'cdr-viewer', params: { to: 'pdf' }, layout: 'app', also: ['pdf'], tags: 'cdr to pdf corel coreldraw convert open cdr online', ready: true },
  { id: 'cdr-to-png', name: 'CDR to PNG', desc: 'Open a CorelDRAW file and save each page as a PNG image at screen or print resolution.', icon: 'image', module: 'cdr-viewer', params: { to: 'png' }, layout: 'app', also: ['image'], tags: 'cdr to png jpg image corel coreldraw convert preview', ready: true },
  { id: 'cdr-to-eps', name: 'CDR to EPS', desc: 'Open a CorelDRAW file and save it as EPS for print shops and other design apps.', icon: 'file-output', module: 'cdr-viewer', params: { to: 'eps' }, layout: 'app', also: ['image'], tags: 'cdr to eps postscript corel coreldraw convert', ready: true },
  { id: 'png-to-eps', name: 'PNG to EPS (vector trace)', desc: 'Trace a PNG, JPG or WebP into vector shapes and save an EPS that CorelDRAW opens with editable curves.', icon: 'file-output', module: 'convert-to-coreldraw', params: { from: 'image', to: 'eps' }, also: ['image'], tags: 'png to eps jpg to eps image to vector trace logo vectorize corel coreldraw', ready: true },
  { id: 'svg-to-eps', name: 'SVG to EPS', desc: 'Convert an SVG to EPS (or AI, PDF) with curves, fills and gradients that CorelDRAW opens for editing.', icon: 'file-output', module: 'convert-to-coreldraw', params: { from: 'svg', to: 'eps' }, also: ['image'], tags: 'svg to eps svg to ai svg to pdf corel coreldraw convert vector', ready: true },
  { id: 'pdf-to-ai', name: 'PDF to AI', desc: 'Save a PDF as an AI file, or rebuild its pages as editable vectors, ready to open in CorelDRAW.', icon: 'file-output', module: 'convert-to-coreldraw', params: { from: 'pdf', to: 'ai' }, also: ['pdf'], tags: 'pdf to ai pdf to eps pdf to svg corel coreldraw convert vector', ready: true },
]
