// Pack pdf-convert: converting to and from PDF, OCR, text extraction and comparison. Default category: pdf.
export const cat = 'pdf'
export default [
  { id: 'pdf-to-word', name: 'PDF to Word', desc: 'Convert a PDF into an editable .docx with headings, lists, tables and pictures kept. Scans can be read with OCR.', icon: 'file-text', tags: 'docx doc convert editable', ready: true },
  { id: 'pdf-to-excel', name: 'PDF to Excel', desc: 'Find the tables in a PDF, preview them on the page and export an .xlsx with real numbers.', icon: 'sheet', also: ['data'], tags: 'xlsx tables spreadsheet', ready: true },
  { id: 'pdf-to-csv', name: 'PDF to CSV', desc: 'Extract tables from a PDF as CSV files, one per table or all together, ready for any spreadsheet.', icon: 'file-spreadsheet', also: ['data'], tags: 'csv tables comma extract', module: 'pdf-to-excel', params: { format: 'csv' }, ready: true },
  { id: 'pdf-to-powerpoint', name: 'PDF to PowerPoint', desc: 'Turn each PDF page into a sharp slide in a .pptx deck, with hidden searchable text and optional notes.', icon: 'presentation', tags: 'pptx slides', ready: true },
  { id: 'pdf-to-image', name: 'PDF to JPG / PNG', desc: 'Export PDF pages as JPG, PNG or WebP at up to 300 dpi, as a ZIP, or stitched into one long image.', icon: 'image', tags: 'jpg png images export render', ready: true },
  { id: 'pdf-to-jpg', name: 'PDF to JPG', desc: 'Save every page of a PDF as a JPG image, with a live size preview, quality and resolution controls.', icon: 'image', tags: 'jpeg images export render', module: 'pdf-to-image', params: { format: 'jpg' }, ready: true },
  { id: 'pdf-to-png', name: 'PDF to PNG', desc: 'Save PDF pages as lossless PNG images, optionally with a transparent background, at up to 300 dpi.', icon: 'image', tags: 'png images export transparent render', module: 'pdf-to-image', params: { format: 'png' }, ready: true },
  { id: 'image-to-pdf', name: 'JPG / PNG to PDF', desc: 'Combine JPG, PNG, WebP and iPhone HEIC images into one PDF with page size, margins, fit and order.', icon: 'file-image', also: ['image'], tags: 'jpg png images photos convert', ready: true },
  { id: 'photo-to-pdf', name: 'Photo to PDF', module: 'image-to-pdf', params: { scan: true }, cat: 'image', desc: 'Turn phone photos into a clean scanned PDF: crop to the page, remove shadows, grayscale or black and white.', icon: 'camera', tags: 'scan photos camera document', ready: true },
  { id: 'word-to-pdf', name: 'Word to PDF', desc: 'Convert .docx files to PDF with the Word layout, headers and footers, tables and pictures kept.', icon: 'file-type', tags: 'docx doc convert', ready: true },
  { id: 'powerpoint-to-pdf', name: 'PowerPoint to PDF', desc: 'Convert .pptx slides to a PDF, one page per slide, with searchable text. Layout is approximated.', icon: 'presentation', also: ['career'], tags: 'pptx ppt slides convert', module: 'pptx-convert', params: { mode: 'pdf' }, ready: true },
  { id: 'ppt-to-images', name: 'PowerPoint to images', desc: 'Export every slide of a .pptx as PNG, JPG or WebP images, up to 4K wide.', icon: 'images', also: ['career'], tags: 'pptx slides png jpg', module: 'pptx-convert', params: { mode: 'images' }, ready: true },
  { id: 'pdf-ocr', name: 'OCR PDF', desc: 'Read scanned PDFs on your device: get a searchable PDF, plain text and a Word file, in many languages.', icon: 'scan-text', mode: 'model', also: ['student'], tags: 'scanned ocr recognize text searchable', ready: true },
  { id: 'pdf-to-text', name: 'PDF to text', desc: 'Extract the text of a PDF in reading order, with layout kept, or line by line. Search, copy and save per page.', icon: 'text', tags: 'extract text txt copy', ready: true },
  { id: 'compare-pdf', name: 'Compare two PDFs', desc: 'Compare two versions page by page: word-level text changes and a pixel diff that shows what moved.', icon: 'git-compare', tags: 'diff difference versions', ready: true },
  { id: 'html-to-pdf', name: 'HTML to PDF', desc: 'Paste or upload HTML and save a paginated, searchable PDF, or print it with the browser.', icon: 'code', also: ['web'], tags: 'html web page', ready: true },
  { id: 'markdown-to-pdf', name: 'Markdown to PDF', desc: 'Write or upload Markdown and export a styled PDF with themes, code highlighting and page numbers.', icon: 'file-code', tags: 'md markdown export', ready: true },
  { id: 'pdf-to-markdown', name: 'PDF to Markdown', desc: 'Convert PDF text into clean Markdown with headings, lists, tables and links. Edit it with a live preview.', icon: 'file-code-2', tags: 'md convert', ready: true },
  { id: 'pdf-to-html', name: 'PDF to HTML', desc: 'Turn a PDF into semantic HTML with headings, lists, tables and optional pictures. Preview and download.', icon: 'file-json-2', also: ['web'], tags: 'html web convert markup', ready: true },
  { id: 'text-to-pdf', name: 'Text to PDF', desc: 'Turn plain text into a PDF with Unicode fonts (Hindi included), margins, line numbers and page numbers.', icon: 'file-type-2', tags: 'txt convert', ready: true },
]
