// Pack student: study, notes, quizzes, citations and maths. Default category: student.
export const cat = 'student'
export default [
  { id: 'notes-to-pdf', name: 'Notes to PDF', desc: 'Turn typed notes or photos of notes into a tidy PDF.', icon: 'notebook', also: ['pdf'], tags: 'notes pdf study', ready: true },
  { id: 'flashcards', name: 'Flashcard generator', desc: 'Make flashcards from notes, study with flip cards, export for Anki.', icon: 'layers', tags: 'flashcards anki study revise', ready: true },
  { id: 'quiz-generator', name: 'Quiz generator', desc: 'Create fill-in-the-blank and short-answer quizzes from your notes.', icon: 'list-checks', tags: 'quiz test questions', ready: true },
  { id: 'mcq-generator', name: 'MCQ generator', desc: 'Generate multiple-choice questions with answers from any text.', icon: 'circle-check', tags: 'mcq multiple choice questions', ready: true },
  { id: 'answer-evaluator', name: 'Answer evaluator', desc: 'Score an answer against a model answer or rubric, with feedback.', icon: 'graduation-cap', tags: 'grade marks evaluate rubric', ready: true },
  { id: 'formula-sheet', name: 'Formula sheet generator', desc: 'Pick formulas for maths, physics, chemistry and print a sheet.', icon: 'sigma', tags: 'formulas cheat sheet maths physics', ready: true },
  { id: 'citation-generator', name: 'Citation generator', desc: 'Cite books, articles, sites and videos in APA, MLA, Chicago, Harvard and IEEE, with DOI and ISBN lookup.', icon: 'quote', also: ['text', 'career'], mode: 'online', tags: 'cite reference doi isbn', ready: true },
  { id: 'bibliography-generator', name: 'Bibliography generator', module: 'citation-generator', params: { list: true }, desc: 'Build a sorted bibliography and copy or export it.', icon: 'library', mode: 'online', tags: 'bibliography references works cited', ready: true },
  { id: 'apa-formatter', name: 'APA formatter', module: 'citation-generator', params: { style: 'apa' }, desc: 'Format references in APA 7th edition.', icon: 'quote', mode: 'online', tags: 'apa citation', ready: true },
  { id: 'mla-formatter', name: 'MLA formatter', module: 'citation-generator', params: { style: 'mla' }, desc: 'Format references in MLA 9th edition.', icon: 'quote', mode: 'online', tags: 'mla citation', ready: true },
  { id: 'chicago-formatter', name: 'Chicago formatter', module: 'citation-generator', params: { style: 'chicago' }, desc: 'Format references in Chicago author-date style.', icon: 'quote', mode: 'online', tags: 'chicago citation author date', ready: true },
  { id: 'harvard-formatter', name: 'Harvard formatter', module: 'citation-generator', params: { style: 'harvard' }, desc: 'Format references in Harvard (Cite Them Right) style.', icon: 'quote', mode: 'online', tags: 'harvard citation reference', ready: true },
  { id: 'ieee-formatter', name: 'IEEE formatter', module: 'citation-generator', params: { style: 'ieee' }, desc: 'Format references in IEEE style.', icon: 'quote', mode: 'online', tags: 'ieee citation engineering', ready: true },
  { id: 'latex-to-pdf', name: 'LaTeX to PDF', desc: 'Render LaTeX math and documents and save as PDF or PNG.', icon: 'square-function', tags: 'latex tex math equations', ready: true },
  { id: 'math-ocr', name: 'Math equation OCR', desc: 'Photo of an equation to LaTeX you can edit and render.', icon: 'scan-line', mode: 'ai', also: ['ai'], tags: 'equation latex photo handwriting', ready: true },
  { id: 'question-paper-to-text', name: 'Question paper to text', desc: 'Scan question papers (images or PDF) into editable, numbered text.', icon: 'file-scan', mode: 'model', tags: 'ocr exam paper questions', ready: true },
  { id: 'lecture-to-notes', name: 'Lecture audio to notes', desc: 'Transcribe a lecture recording and turn it into study notes.', icon: 'audio-lines', mode: 'model', also: ['ai'], tags: 'lecture recording notes transcribe', ready: true },
  { id: 'scientific-calculator', name: 'Scientific calculator', desc: 'Trig, logs, powers, memory and history, keyboard friendly.', icon: 'calculator', also: ['calc'], tags: 'calculator sin cos log', ready: true },
  { id: 'graph-plotter', name: 'Graph plotter', desc: 'Plot functions like y = sin(x) and x^2 - 3 with zoom and pan.', icon: 'chart-spline', also: ['calc'], tags: 'graph function plot desmos', ready: true },
  { id: 'gpa-calculator', name: 'GPA / CGPA calculator', desc: 'Compute GPA, CGPA and convert CGPA to percentage.', icon: 'award', also: ['calc'], tags: 'gpa cgpa sgpa percentage marks', ready: true },
  { id: 'percentage-marks', name: 'Marks percentage calculator', desc: 'Percentage, grade and total from subject marks.', icon: 'percent', tags: 'marks percentage grade', ready: true },
  { id: 'study-planner', name: 'Study timetable planner', desc: 'Plan subjects across days before exams and print the timetable.', icon: 'calendar-clock', also: ['personal'], tags: 'timetable exam schedule', ready: true },
  { id: 'molar-mass-calculator', name: 'Molar mass calculator', desc: 'Molar mass and mass percent of any formula, with a grams to moles converter.', icon: 'flask-conical', also: ['calc'], tags: 'chemistry molar mass moles formula weight composition', ready: true },
  { id: 'chemical-equation-balancer', name: 'Chemical equation balancer', desc: 'Balance chemical equations with whole-number coefficients and an atom check.', icon: 'scale', tags: 'chemistry balance equation stoichiometry reaction', ready: true },
  { id: 'quadratic-solver', name: 'Quadratic equation solver', desc: 'Solve ax2 + bx + c = 0 with steps, exact roots, vertex and a graph.', icon: 'square-function', also: ['calc'], tags: 'quadratic equation roots discriminant parabola algebra', ready: true },
]
